# Generated by Django 5.0.1 on 2024-01-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcaseid', models.CharField(max_length=100)),
                ('usecase', models.CharField(max_length=400)),
                ('testresult', models.CharField(max_length=50)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
