# Generated by Django 5.0.1 on 2024-01-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_testrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcaseid', models.CharField(max_length=50)),
                ('usecase', models.CharField(max_length=400)),
            ],
        ),
    ]
