# Generated by Django 5.0.1 on 2024-02-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_fcpawsresult_fcpazureresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycleid', models.CharField(max_length=10)),
                ('service_typ', models.CharField(max_length=10)),
                ('cloud_provider', models.CharField(max_length=10)),
                ('pass_amt', models.CharField(max_length=50)),
                ('fail_amt', models.CharField(max_length=400)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
