# Generated by Django 5.0.1 on 2024-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_serviceresult_cloudservicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('stories', models.CharField(max_length=5000)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
