# Generated by Django 5.0.1 on 2024-03-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_sccawsresult_percent_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresults',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
