# Generated by Django 5.0.1 on 2024-03-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_testresults_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcpawsresult',
            name='percent_pass',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='fcpazureresult',
            name='percent_pass',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sccazureresult',
            name='percent_pass',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fcpawsresult',
            name='fail_amt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fcpazureresult',
            name='fail_amt',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sccazureresult',
            name='fail_amt',
            field=models.CharField(max_length=50),
        ),
    ]
