# Generated by Django 5.0.1 on 2024-03-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_fcpawsresult_percent_pass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('cycleid', models.CharField(default=None, max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('stories', models.CharField(max_length=5000)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ReleaseTag',
        ),
    ]
